# Generated by Django 4.2.3 on 2023-08-17 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=250)),
                ('Author_name', models.CharField(max_length=250)),
                ('Price', models.CharField(max_length=250)),
                ('Publisher_ID', models.CharField(max_length=25)),
                ('Stock', models.CharField(max_length=250)),
                ('Book_Image', models.ImageField(null=True, upload_to='image/')),
                ('Book_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50)),
                ('Book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib_app.bookmodal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50)),
                ('totalprice', models.CharField(max_length=255)),
                ('Book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib_app.bookmodal')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib_app.cartmodal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rent_date', models.DateField(default=django.utils.timezone.now)),
                ('Due_date', models.DateField()),
                ('Rental_period', models.CharField(max_length=50)),
                ('Rental_books_quantity', models.CharField(max_length=50)),
                ('Returned_date', models.DateField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('User_Rent_Book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib_app.bookmodal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_number', models.CharField(max_length=10)),
                ('User_date', models.DateField(auto_now_add=True)),
                ('User_Book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib_app.bookmodal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TotalPriceModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.CharField(max_length=250)),
                ('Book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib_app.bookmodal')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib_app.ordermodal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fine', models.CharField(max_length=250)),
                ('Return_date', models.DateField(blank=True, null=True)),
                ('Rent_Book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib_app.bookmodal')),
                ('Rent_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib_app.rentmodal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentHistoryModaltesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rent_date', models.DateField(default=django.utils.timezone.now)),
                ('Due_date', models.DateField()),
                ('Rental_period', models.CharField(max_length=50)),
                ('Rental_books_quantity', models.CharField(max_length=50)),
                ('Returned_date', models.DateField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('User_Rent_Book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib_app.bookmodal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FineModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fine', models.CharField(max_length=250)),
                ('is_paid', models.BooleanField(default=False)),
                ('Rent_Book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib_app.bookmodal')),
                ('Rent_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib_app.rentmodal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
