# Generated by Django 4.2.3 on 2023-08-31 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0004_ordersmodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodal',
            name='BooksName',
            field=models.CharField(default=django.utils.timezone.now, max_length=600),
            preserve_default=False,
        ),
    ]
